services:
  - type: web
    name: parts-catalogue-system
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html